### ISSUE TITLE
Mosca log analysis !?

### ISSUE THREAD

**Issue by behrad** [sguilly/mqtt-influxdb#1]
Can i use this to stream Mosca bunyan logs into influxDB?

**Comment by sguilly** [comment]
Yes, you could create a bunyan stream to send all logs as events to a mqtt server. Then, use this module to subscribe to the log topic to insert log into influxDB. (See : https://github.com/trentm/node-bunyan/blob/master/examples/raw-stream.js)

MqttStream.prototype.write = function (rec) {
    //console.log('emit mqtt');
    this.clientMqtt.publish('myLoggerName/log',JSON.stringify(rec));
};

**Comment by behrad** [comment]
great answer @sguilly , however I was expecting to directly use an influxDB stream or use the influxDB stream inside mqtt-influxdb if any :)
